# Generated by Django 3.2.8 on 2021-10-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='gender',
            field=models.CharField(choices=[('one', 'Female'), ('two', 'Male')], default='private', max_length=20),
        ),
    ]
